gwegv

diff --git a/install_kuali_coeus b/install_kuali_coeus
--- a/install_kuali_coeus
+++ b/install_kuali_coeus
@@ -45,7 +45,7 @@ ORACLE_SQL_FILES_FOLDER="${CURRENT_WORKING_DIR}/workspace/kc/coeus-db/coeus-db-s
 
 # Oracle Settings
 SETUP_FILES_FOLDER="${CURRENT_WORKING_DIR}/setup_files"
-ORACLE_DRIVER_NAME="ojdbc6.jar"
+ORACLE_DRIVER_NAME="ojdbc7.jar"
 
 # Kuali Release File
 KC_CONFIG_XML_LOC="/opt/kuali/main/dev"
@@ -57,8 +57,8 @@ CLEANUP_LOCATIONS="/opt/apache-tomcat /opt/kuali ${CURRENT_WORKING_DIR}/SQL_LOGS
 KC_PROJECT_WAR_NAME="kc-dev.war"
 KC_PROJECT_FOLDER="${CURRENT_WORKING_DIR}/workspace/kc"
 KC_PROJECT_LINK="https://github.com/kuali/kc"
-KC_PROJECT_RICE_XML="https://goo.gl/8hnZYq"
-KC_PROJECT_COEUS_XML="https://goo.gl/nN3jNy"
+KC_PROJECT_RICE_XML="http://www.kuali.erafiki.com/${KC_PROJECT_VERSION}/xml_files/rice-xml-${KC_PROJECT_VERSION}.zip"
+KC_PROJECT_COEUS_XML="http://www.kuali.erafiki.com/${KC_PROJECT_VERSION}/xml_files/coeus-xml-${KC_PROJECT_VERSION}.zip"
 # SchemaSpy Project
 SCHEMASPY_PROJECT_FORLDER="${CURRENT_WORKING_DIR}/workspace/schemaspy"
 SCHEMASPY_PROJECT_LINK="https://github.com/kuali/schemaspy"
@@ -73,6 +73,19 @@ KC_S2SGEN_PROJECT_FORLDER="${CURRENT_WORKING_DIR}/workspace/kc-s2sgen"
 KC_S2SGEN_PROJECT_LINK="https://github.com/kuali/kc-s2sgen"
 
 # FUNCTIONS
+function install_this_package () {
+	if [ -f /etc/debian_version ]; then
+		apt-get update
+		apt-get install -y $1
+	elif [ -f /etc/redhat-release ]; then
+		yum install -y $1
+	fi
+}
+
+function check_if_package_is_installed () {
+	command -v $1 >/dev/null 2>&1 || { echo >&2 "Couldn't find $1 on your system. Installing it: "; install_this_package $1; }
+}
+
 function clone_kuali_coeus {
 	if [ -d ${KC_PROJECT_FOLDER} ]; then
 		echo
@@ -89,13 +102,25 @@ function clone_kuali_coeus {
 		echo "-------------------------------"
 		mkdir -p ${CURRENT_WORKING_DIR}/workspace
 		cd ${CURRENT_WORKING_DIR}/workspace
+		check_if_package_is_installed git
 		git clone ${KC_PROJECT_LINK}
 	fi
 }
 
 function compile_kuali {
-	
-	
+	if [ "$mysql_or_oracle" -eq "2" ]; then
+		if [ -f ${SETUP_FILES_FOLDER}/${ORACLE_DRIVER_NAME} ]; then                                                      
+			echo " Good. Found your Oracle driver, ${ORACLE_DRIVER_NAME} in ${SETUP_FILES_FOLDER}"                   
+		else                                                                                                             
+			echo                                                                                                     
+			echo "I can't find your Oracle driver, ${ORACLE_DRIVER_NAME}, in ${SETUP_FILES_FOLDER}"                  
+			echo                                                                                                     
+			echo "Either copy your Oracle driver, ${ORACLE_DRIVER_NAME}, in ${SETUP_FILES_FOLDER}"                   
+			echo "or set 'ORACLE_DRIVER_NAME' in this script. "                                                      
+			echo                                                                                                     
+			exit                                                                                                     
+		fi
+	fi
 	# Clone the Kuali Project
 	clone_kuali_coeus
 
@@ -110,14 +135,14 @@ function compile_kuali {
 	if [ -d ${SCHEMASPY_PROJECT_FORLDER} ]; then
 		cd ${SCHEMASPY_PROJECT_FORLDER}
 		git checkout tags/schemaspy-${SCHEMASPY_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	else
 		mkdir -p ${CURRENT_WORKING_DIR}/workspace
 		cd ${CURRENT_WORKING_DIR}/workspace
 		git clone ${SCHEMASPY_PROJECT_LINK}
 		cd ${SCHEMASPY_PROJECT_FORLDER}
 		git checkout tags/schemaspy-${SCHEMASPY_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	fi
 
 	cd ..
@@ -126,14 +151,14 @@ function compile_kuali {
 	if [ -d ${KC_RICE_PROJECT_FORLDER} ]; then
 		cd ${KC_RICE_PROJECT_FORLDER}
 		git checkout tags/rice-${KC_RICE_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	else
 		mkdir -p ${CURRENT_WORKING_DIR}/workspace
 		cd ${CURRENT_WORKING_DIR}/workspace
 		git clone ${KC_RICE_PROJECT_LINK}
 		cd ${KC_RICE_PROJECT_FORLDER}
 		git checkout tags/rice-${KC_RICE_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+	mvn -DskipTests clean install -Dgrm.off=true
 	fi
 
 	cd ..
@@ -142,14 +167,14 @@ function compile_kuali {
 	if [ -d ${KC_API_PROJECT_FORLDER} ]; then
 		cd ${KC_API_PROJECT_FORLDER}
 		git checkout tags/coeus-api-${KC_API_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	else
 		mkdir -p ${CURRENT_WORKING_DIR}/workspace
 		cd ${CURRENT_WORKING_DIR}/workspace
 		git clone ${KC_API_PROJECT_LINK}
 		cd ${KC_API_PROJECT_FORLDER}
 		git checkout tags/coeus-api-${KC_API_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	fi
 
 	cd ..
@@ -158,58 +183,75 @@ function compile_kuali {
 	if [ -d ${KC_S2SGEN_PROJECT_FORLDER} ]; then
 		cd ${KC_S2SGEN_PROJECT_FORLDER}
 		git checkout tags/coeus-s2sgen-${KC_S2SGEN_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	else
 		mkdir -p ${CURRENT_WORKING_DIR}/workspace
 		cd ${CURRENT_WORKING_DIR}/workspace
 		git clone ${KC_S2SGEN_PROJECT_LINK}
 		cd ${KC_S2SGEN_PROJECT_FORLDER}
 		git checkout tags/coeus-s2sgen-${KC_S2SGEN_PROJECT_VER}
-		mvn clean compile source:jar javadoc:jar install -Dgrm.off=true
+		mvn -DskipTests clean install -Dgrm.off=true
 	fi
 
 	cd ..
 
 	# BUILD KUALI COEUS
 	cd ${KC_PROJECT_FOLDER}
-	
+	if [ "$mysql_or_oracle" -eq "1" ]; then
+		mvn -DskipTests clean install -Dgrm.off=true
+	fi
+	if [ "$mysql_or_oracle" -eq "2" ]; then
+		mvn install:install-file -Dfile=${SETUP_FILES_FOLDER}/${ORACLE_DRIVER_NAME} -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0.2 -Dpackaging=jar
+		mvn -P oracle clean compile source:jar javadoc:jar install -Dgrm.off=true
+	fi
 
-	
+	# Create a copy of the war file and the XML file to ingest
+	echo
 	echo "Copying a copy of the war file to the ${CURRENT_WORKING_DIR}/DOWNLOADS folder"
 	mkdir -p ${CURRENT_WORKING_DIR}/DOWNLOADS
 	cp ${CURRENT_WORKING_DIR}/workspace/kc/coeus-webapp/target/coeus-webapp-${KC_PROJECT_VER}.war ${CURRENT_WORKING_DIR}/DOWNLOADS/${KC_PROJECT_WAR_NAME}
 	echo
-	
-}
-
-function install_this_package () {
-	if [ -f /etc/debian_version ]; then
-		apt-get update
-		apt-get install -y $1
-	elif [ -f /etc/redhat-release ]; then
-		yum install -y $1
-	fi
-}
-
-function check_if_package_is_installed () {
-	command -v $1 >/dev/null 2>&1 || { echo >&2 "Couldn't find $1 on your system. Installing it: "; install_this_package $1; }
+	echo "Creating a copy of the XML file to ingest in the ${CURRENT_WORKING_DIR}/DOWNLOADS folder"
+	sleep 3
+	rm -f ${CURRENT_WORKING_DIR}/DOWNLOADS/rice-xml-${KC_PROJECT_VERSION}.zip
+	rm -f ${CURRENT_WORKING_DIR}/DOWNLOADS/coeus-xml-${KC_PROJECT_VERSION}.zip
+	jar xf ${CURRENT_WORKING_DIR}/workspace/kc/coeus-db/coeus-db-xml/target/coeus-db-xml-${KC_PROJECT_VER}.jar
+	zip -r ${CURRENT_WORKING_DIR}/DOWNLOADS/rice-xml-${KC_PROJECT_VERSION}.zip org/kuali/coeus/rice-xml/
+	zip -r ${CURRENT_WORKING_DIR}/DOWNLOADS/coeus-xml-${KC_PROJECT_VERSION}.zip org/kuali/coeus/coeus-xml/
+	rm -fr META-INF org
 }
 
 function install_build_packages {
 	# Debian/Ubuntu Packages
 	if [ -f /etc/debian_version ]; then
 			# Install Java and Maven on a Debian System
+			apt-get update
+			apt-get install -y software-properties-common
+			if [ "$(cat /etc/lsb-release | grep RELEASE | sed 's/.*=//')" == "12.04" ]; then
+				if [ ! -f /etc/apt/sources.list.d/webupd8team-java-precise.list ]; then
+					apt-get install -y python-software-properties
+					add-apt-repository -y ppa:webupd8team/java
+					echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
+					apt-get install -y oracle-java8-installer
+				fi
+			fi
 			if [ "$(cat /etc/lsb-release | grep RELEASE | sed 's/.*=//')" == "14.04" ]; then
-				if [ ! -f /etc/apt/trusted.gpg.d/openjdk-r-ppa.gpg ]; then
-					apt-get update
-					apt-get install -y software-properties-common
+				if [ ! -f /etc/apt/sources.list.d/openjdk-r-ppa-trusty.list ]; then
 					add-apt-repository -y ppa:openjdk-r/ppa
 				fi
 			fi
+			if [ ! -f /etc/apt/sources.list.d/andrei-pozolotin-maven3-trusty.list ]; then
+				add-apt-repository -y ppa:andrei-pozolotin/maven3
+			fi
 			apt-get update
-			apt-get install -y openjdk-8-jdk maven git zip
+			apt-get install -y openjdk-8-jdk maven3 git zip npm
 			# To ensure to use java version 8
-			apt-get remove -y openjdk-7-jre-headless
+			# apt-get remove -y openjdk-7-jre-headless
+			update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
+			update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
+			if [ "$(cat /etc/lsb-release | grep RELEASE | sed 's/.*=//')" == "12.04" ]; then
+				apt-get install -y oracle-java8-set-default
+			fi
 	fi
 
 	# RedHat/Centos Packages
@@ -218,7 +260,8 @@ function install_build_packages {
 				yum install -y wget
 				wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
 			fi
-				yum install -y java-1.8.0-openjdk-devel.x86_64 apache-maven git zip
+				yum install -y epel-release
+				yum install -y java-1.8.0-openjdk-devel.x86_64 apache-maven git zip npm make
 				# Set the correct java version, version 8
 				update-alternatives --set java /usr/lib/jvm/java-1.8.*-openjdk-1.8.*.x86_64/jre/bin/java
 				update-alternatives --set javac /usr/lib/jvm/java-1.8.*-openjdk-1.8.*.x86_64/bin/javac
@@ -235,7 +278,9 @@ function install_packages {
 		apt-get update
 		apt-get install -y wget zip unzip openjdk-8-jdk git tar graphviz
 		# To ensure to use java version 8
-		apt-get remove -y openjdk-7-jre-headless
+		# apt-get remove -y openjdk-7-jre-headless
+		update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
+		update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac
 	elif [ -f /etc/redhat-release ]; then
 		yum install -y wget zip unzip java-1.8.0-openjdk git tar graphviz
 	fi
@@ -628,7 +673,7 @@ function ask_user_information {
 	#### MySQL SECTION ###
 	if [ "$mysql_or_oracle" -eq "1" ]; then
 		mysql_or_oracle_choice="MySQL"
-		KC_PROJECT_WAR_LINK="https://goo.gl/RjyrIw"
+		KC_PROJECT_WAR_LINK="http://www.kuali.erafiki.com/${KC_PROJECT_VERSION}/mysql/kc-dev.war"
 		KC_PROJECT_WAR_NAME="kc-dev.war"
 		echo
 		echo "Enter KC Database Username (Default: kcusername)"
@@ -686,7 +731,7 @@ function ask_user_information {
 	#### ORACLE SECTION ###
 	elif [ "$mysql_or_oracle" -eq "2" ]; then
 		mysql_or_oracle_choice="Oracle"
-		KC_PROJECT_WAR_LINK="https://goo.gl/Y4D8kg"
+		KC_PROJECT_WAR_LINK="http://www.kuali.erafiki.com/${KC_PROJECT_VERSION}/oracle/kc-dev.war"
 		KC_PROJECT_WAR_NAME="kc-dev.war"
 		echo
 		echo "Enter KC Database Username (Default: system)"
@@ -782,31 +827,36 @@ function main_menu {
 		[1] )
 			echo
 			clean_up_system
-			
+			ask_user_information
 
 			echo "Compiling and Installing Kuali Coeus for you"
 			echo "============================================"
 			echo "Installing Packages"
 			sleep 1
-			
-			
+			install_build_packages
+			install_packages
 			echo "Compiling Kuali Coeus"
 			sleep 1
 			compile_kuali
 			echo "Stopping the firewall"
 			sleep 1
-			
-			
+			stop_firewall
+			echo "Checking/Installing database"
 			sleep 1
 			clone_kuali_coeus
-			
-			
-			
-			
-			
+			echo "Setting the Kuali Coeus Database"
+			sleep 1
+			# Make sure that sqlplus is installed for oracle
+			if [ "$mysql_or_oracle" -eq "2" ]; then
+				command -v sqlplus >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
+			fi
+			setup_kuali_database
+			echo "Setting up tomcat"
+			sleep 1
+			setup_tomcat
 			echo "Setting and starting the KC application"
 			sleep 1
-			
+			setup_kc_application
 			;;
 
 		[2] )
@@ -869,7 +919,7 @@ function main_menu {
 			sleep 1
 			# Make sure that sqlplus is installed for oracle
 			if [ "$mysql_or_oracle" -eq "2" ]; then
-				command -v sqlplus64 >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
+				command -v sqlplus >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
 			fi
 			setup_kuali_database
 			echo "Setting up tomcat"
@@ -898,7 +948,7 @@ function main_menu {
 			sleep 1
 			# Make sure that sqlplus is installed for oracle
 			if [ "$mysql_or_oracle" -eq "2" ]; then
-				command -v sqlplus64 >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
+				command -v sqlplus >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
 			fi
 			setup_kuali_database
 			;;
@@ -963,7 +1013,7 @@ function main_menu {
 			echo "==================================="
 			# Make sure that sqlplus is installed for oracle
 			if [ "$mysql_or_oracle" -eq "2" ]; then
-				command -v sqlplus64 >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
+				command -v sqlplus >/dev/null 2>&1 || { echo >&2 "Couldn't find sqlplus64 on your system. Installing it: "; install_sqlplus; }
 			fi
 			run_sql_database_scripts
 			;;
